//This code was made with help from Greg Nemes, www.workshop.co 

//When the document is ready, run this loop:
//for as long as i is 0 and less than the length of quotesData, run this code
$(document).ready(function () {
    for (var i = 0; i < quotesData.length; i++) {
        
        //if the current property consent of quotesData is yes, put it in an array called consentQuotes with just the quote and the id. 
        if (quotesData[i].consent == "yes") {
            consentQuotes.push({
                quote: quotesData[i].quote,
                id: quotesData[i].id
            });

        }

        //if the current property lgbtq of quotesData is yes, put it in an array called lgbtqQuotes with just the quote and the id. 
        if (quotesData[i].lgbtq == "yes") {
            lgbtqQuotes.push({
                quote: quotesData[i].quote,
                id: quotesData[i].id
            });
        }

        //if the current property sexEdu of quotesData is yes, put it in an array called sexEduQuotes with just the quote and the id. 
        if (quotesData[i].sexEdu == "yes") {
            sexEduQuotes.push({
                quote: quotesData[i].quote,
                id: quotesData[i].id
            });
        }
        
        //if the current property sexExp of quotesData is yes, put it in an array called sexExpQuotes with just the quote and the id. 
        if (quotesData[i].sexExp == "yes") {
            sexExpQuotes.push({
                quote: quotesData[i].quote,
                id: quotesData[i].id
            });
        }
        
        //if the current property sexAssault of quotesData is yes, put it in an array called sexAssaultQuotes with just the quote and the id. 
        if (quotesData[i].sexAssault == "yes") {
            sexAssaultQuotes.push({
                quote: quotesData[i].quote,
                id: quotesData[i].id
            });
        }

    }
});


//create array to track the consent relevant quotes
var consentQuotes = [];

var lgbtqQuotes = [];

var sexEduQuotes = [];

var sexAssaultQuotes = [];

var sexExpQuotes = [];


//When any of the buttons with the class .quoteBtn are clicked, run this function with the argument (event). 
$(".quoteBtn").click(
    function (event) {
        
//        The variable topic is determined by the topic property of the button clicked on.
        var topic = $(this).data("topic");

//        run the function showTopic with the argument topic
        showTopic(topic);

//        Establish variables to be defined later.
        var randomNum;
        var quote;
        var author;
        var array;

//This code basically says that if the topic is equal to (any of the different topics) then set the array to whichever array houses that topic
        if (topic === "consent") {
            array = consentQuotes;
        }
        if (topic === "lgbtq") {
            array = lgbtqQuotes;
        }
        if (topic === "sexEdu") {
            array = sexEduQuotes;
        }
        if (topic === "sexExp") {
            array = sexExpQuotes;
        }
        if (topic === "sexAssault") {
            array = sexAssaultQuotes;
        }

//        The variable randomNum generates a random number by using the method math.floor(), which will return a number less than or equal to whatever number is its parameter. In this case, the number being entered is a random number generated by Math.random multiplied by the length of whichever array was picked.
        randomNum = Math.floor(Math.random() * array.length);
        
//        Quote adds quotes to the outside of the quote generated by the array index of randomNum.
        quote = '"' + array[randomNum].quote + '"';
        
//        Author adds an mdash to the author of the same array index at randomNum
        author = " —" + array[randomNum].id;
        
//        http://www.scriptingmaster.com/javascript/formatting-text-JavaScript.asp
//        Using the method bold() makes the author stand out from the quoted text
        authorStyled = author.bold();

//        This selects the id of the topic and changes the html to the quote and author.
        $("#" + topic).html(quote + authorStyled);

    }

);
//
//This function enters the argument of topic, and says to select the class .topic and add the class .hidden to it, then select the id of the topic selected and remove the class .hidden.
function showTopic(topic) {
    $(".topic").addClass("hidden");
    $("#" + topic).removeClass("hidden");
}
